kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: k8s-workshop
  name: developer-role
rules:
- apiGroups: [“”] # “” indicates the core API group
  resources: [“pods”]
  verbs: [“get”, “watch”, “list”]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-manager-binding
  namespace: k8s-workshop
subjects:
- kind: User
  name: developer
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: k8s-workshop
  name: tester-role
rules:
- apiGroups: [“”] # “” indicates the core API group
  resources: [“deploymnets”]
  verbs: [“get”]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-manager-binding
  namespace: k8s-workshop
subjects:
- kind: User
  name: tester
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
